<?php

declare(strict_types=1);

namespace IntentPHP\Guard\Report;

use Illuminate\Console\Command;
use IntentPHP\Guard\Scan\Finding;

class MarkdownReporter
{
    public function __construct(
        private readonly Command $command,
    ) {}

    /**
     * @param Finding[] $findings All findings including suppressed
     * @param array<string, mixed> $options
     */
    public function report(array $findings, array $options = []): void
    {
        $this->command->line($this->render($findings, $options));
    }

    /**
     * Render the full markdown report as a string.
     *
     * @param Finding[] $findings All findings including suppressed
     * @param array<string, mixed> $options
     */
    public function render(array $findings, array $options = []): string
    {
        $includeSuppressed = (bool) ($options['include_suppressed'] ?? false);
        $includeAiPatch = (bool) ($options['include_ai_patch'] ?? false);
        $scanMode = (string) ($options['scan_mode'] ?? 'full');
        $baselineUsed = (bool) ($options['baseline_used'] ?? false);
        $max = (int) ($options['max'] ?? 0);

        $active = array_values(array_filter($findings, fn (Finding $f) => ! $f->isSuppressed()));
        $suppressed = array_values(array_filter($findings, fn (Finding $f) => $f->isSuppressed()));

        $lines = [];

        // Header
        $lines[] = '## Guard Security Scan Report';
        $lines[] = '';

        // Summary table
        $lines[] = '| Metric | Value |';
        $lines[] = '|--------|-------|';
        $routeScanMode = (string) ($options['route_scan_mode'] ?? 'full');

        $lines[] = '| Scan mode | ' . $scanMode . ' |';
        $lines[] = '| Route scan mode | ' . $routeScanMode . ' |';
        $lines[] = '| Baseline | ' . ($baselineUsed ? 'yes' : 'no') . ' |';
        $lines[] = '| Total findings | ' . count($findings) . ' |';
        $lines[] = '| Active | ' . count($active) . ' |';
        $lines[] = '| HIGH | ' . count(array_filter($active, fn (Finding $f) => $f->severity === 'high')) . ' |';
        $lines[] = '| MEDIUM | ' . count(array_filter($active, fn (Finding $f) => $f->severity === 'medium')) . ' |';
        $lines[] = '| Suppressed | ' . count($suppressed) . ' |';
        $lines[] = '';

        if (empty($active)) {
            $lines[] = '> No active findings. All clear!';
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '*Generated by [IntentPHP Guard](https://github.com/drnasin/intentphp)*';

            return implode("\n", $lines);
        }

        // Group active findings by check
        $grouped = [];
        foreach ($active as $finding) {
            $grouped[$finding->check][] = $finding;
        }

        foreach ($grouped as $check => $checkFindings) {
            $displayed = $max > 0 ? array_slice($checkFindings, 0, $max) : $checkFindings;
            $truncated = count($checkFindings) - count($displayed);

            $lines[] = "### {$check} (" . count($checkFindings) . ')';
            $lines[] = '';

            foreach ($displayed as $finding) {
                $location = '';
                if ($finding->file) {
                    $relPath = $this->relativePath($finding->file);
                    $location = "`{$relPath}" . ($finding->line ? ":{$finding->line}" : '') . '`';
                }

                $severity = strtoupper($finding->severity);
                $lines[] = "- **{$severity}** {$finding->message}";

                if ($location) {
                    $lines[] = "  - File: {$location}";
                }

                if (! empty($finding->context['action'])) {
                    $lines[] = "  - Action: `{$finding->context['action']}`";
                }

                if (! empty($finding->context['policy'])) {
                    $lines[] = "  - Policy: `{$finding->context['policy']}`";
                }

                if (! empty($finding->context['ability'])) {
                    $lines[] = "  - Ability: `{$finding->context['ability']}`";
                }

                if (! empty($finding->context['snippet'])) {
                    $lines[] = "  - Code: `{$finding->context['snippet']}`";
                }

                if ($finding->fix_hint) {
                    $lines[] = "  - Fix: {$finding->fix_hint}";
                }

                if ($finding->ai_suggestion !== null) {
                    $aiText = mb_strlen($finding->ai_suggestion) > 2000
                        ? mb_substr($finding->ai_suggestion, 0, 2000) . "\n\n*(truncated)*"
                        : $finding->ai_suggestion;

                    $lines[] = '  <details><summary>AI Suggested Fix</summary>';
                    $lines[] = '';
                    $lines[] = '  ' . str_replace("\n", "\n  ", $aiText);
                    $lines[] = '';
                    $lines[] = '  </details>';
                }

                if ($includeAiPatch && ! empty($finding->context['ai_patch'])) {
                    $patchText = (string) $finding->context['ai_patch'];
                    if (mb_strlen($patchText) > 3000) {
                        $patchText = mb_substr($patchText, 0, 3000) . "\n\n*(truncated)*";
                    }

                    $lines[] = '  <details><summary>AI Patch Proposal (not applied)</summary>';
                    $lines[] = '';
                    $lines[] = '  ```diff';
                    $lines[] = '  ' . str_replace("\n", "\n  ", $patchText);
                    $lines[] = '  ```';
                    $lines[] = '';
                    $lines[] = '  </details>';
                }

                $lines[] = '';
            }

            if ($truncated > 0) {
                $lines[] = "*... and {$truncated} more finding(s) in this group.*";
                $lines[] = '';
            }
        }

        // Suppressed section
        if ($includeSuppressed && ! empty($suppressed)) {
            $lines[] = '<details><summary>Suppressed findings (' . count($suppressed) . ')</summary>';
            $lines[] = '';

            foreach ($suppressed as $finding) {
                $lines[] = "- ~~{$finding->message}~~ ({$finding->suppressed_reason})";
            }

            $lines[] = '';
            $lines[] = '</details>';
            $lines[] = '';
        }

        $lines[] = '---';
        $lines[] = '*Generated by [IntentPHP Guard](https://github.com/drnasin/intentphp)*';

        return implode("\n", $lines);
    }

    private function relativePath(string $absolutePath): string
    {
        $path = str_replace('\\', '/', $absolutePath);

        if (preg_match('#(app/.*)$#', $path, $m)) {
            return $m[1];
        }

        if (preg_match('#(routes/.*)$#', $path, $m)) {
            return $m[1];
        }

        return basename($path);
    }
}
