<?php

declare(strict_types=1);

namespace IntentPHP\Guard\Patch;

use IntentPHP\Guard\AI\AiClientInterface;
use IntentPHP\Guard\AI\PromptBuilder;
use IntentPHP\Guard\Scan\Finding;

class AiPatchGenerator
{
    public function __construct(
        private readonly AiClientInterface $client,
        private readonly PromptBuilder $promptBuilder,
        private readonly PatchBuilder $patchBuilder,
    ) {}

    /**
     * Generate an AI-assisted patch for a finding.
     * Returns a Patch with diff text, or null if generation fails.
     * When AI produces text that can't be structured as a diff, a note file content is returned via $noteOut.
     */
    public function generate(Finding $finding, ?string &$noteOut = null): ?Patch
    {
        $noteOut = null;

        if (! $this->client->isAvailable()) {
            return null;
        }

        $prompt = $this->promptBuilder->buildFixPrompt($finding);
        $response = $this->client->generate($prompt);

        if (str_starts_with($response, '[AI')) {
            return null;
        }

        // Try to extract a diff block from the AI response
        $diff = $this->extractDiff($response);

        if ($diff !== null && $finding->file) {
            return new Patch(
                file: $finding->file,
                original: '',
                suggested: '',
                diff: "# Generated by Guard (AI-assisted). Review before applying.\n" . $diff,
            );
        }

        // Try to build a patch from code blocks in the response
        $codeBlock = $this->extractCodeBlock($response);

        if ($codeBlock !== null && $finding->file && $finding->line) {
            $snippet = $finding->context['snippet'] ?? '';

            if ($snippet !== '' && $snippet !== $codeBlock) {
                $patch = $this->patchBuilder->build(
                    $finding->file,
                    $snippet,
                    $codeBlock,
                    $finding->line,
                );

                return new Patch(
                    file: $patch->file,
                    original: $patch->original,
                    suggested: $patch->suggested,
                    diff: "# Generated by Guard (AI-assisted). Review before applying.\n" . $patch->diff,
                );
            }
        }

        // Fallback: return the full AI response as a note
        $noteOut = "# Guard AI Fix Suggestion\n\n";
        $noteOut .= "**Check:** {$finding->check}\n";
        $noteOut .= "**File:** " . ($finding->file ?? 'N/A') . "\n";
        $noteOut .= "**Line:** " . ($finding->line ?? 'N/A') . "\n\n";
        $noteOut .= "## AI Response\n\n";
        $noteOut .= $response . "\n";

        return null;
    }

    private function extractDiff(?string $text): ?string
    {
        if ($text === null) {
            return null;
        }

        // Match a unified diff block (```diff ... ``` or raw --- a/ ... +++ b/)
        if (preg_match('/```diff\s*\n(.*?)```/s', $text, $m)) {
            return trim($m[1]);
        }

        if (preg_match('/(---\s+a\/.*?\n\+\+\+\s+b\/.*?\n@@.*?(?:\n[-+ ].*)*)/s', $text, $m)) {
            return trim($m[1]);
        }

        return null;
    }

    private function extractCodeBlock(?string $text): ?string
    {
        if ($text === null) {
            return null;
        }

        // Match the last ```php ... ``` block (most likely the fix)
        if (preg_match_all('/```php\s*\n(.*?)```/s', $text, $matches)) {
            $blocks = $matches[1];
            return trim(end($blocks));
        }

        return null;
    }
}
