<?php

declare(strict_types=1);

namespace Tests\Unit;

use IntentPHP\Guard\AI\AiClientInterface;
use IntentPHP\Guard\AI\PromptBuilder;
use IntentPHP\Guard\Patch\AiPatchGenerator;
use IntentPHP\Guard\Patch\PatchBuilder;
use IntentPHP\Guard\Scan\Finding;
use PHPUnit\Framework\TestCase;

class AiPatchGeneratorTest extends TestCase
{
    public function test_returns_null_when_client_is_unavailable(): void
    {
        $client = $this->createMock(AiClientInterface::class);
        $client->method('isAvailable')->willReturn(false);

        $generator = new AiPatchGenerator(
            $client,
            new PromptBuilder(),
            new PatchBuilder(),
        );

        $finding = Finding::high(
            check: 'route-authorization',
            message: 'Test finding',
            file: '/app/Http/Controllers/TestController.php',
            line: 10,
            context: [],
            fix_hint: 'Add auth',
        );

        $this->assertNull($generator->generate($finding));
    }

    public function test_returns_null_when_ai_response_starts_with_bracket_ai(): void
    {
        $client = $this->createMock(AiClientInterface::class);
        $client->method('isAvailable')->willReturn(true);
        $client->method('generate')->willReturn('[AI unavailable — GUARD_AI_API_KEY not set.]');

        $generator = new AiPatchGenerator(
            $client,
            new PromptBuilder(),
            new PatchBuilder(),
        );

        $finding = Finding::high(
            check: 'route-authorization',
            message: 'Test finding',
            file: '/app/Http/Controllers/TestController.php',
            line: 10,
            context: [],
            fix_hint: 'Add auth',
        );

        $this->assertNull($generator->generate($finding));
    }

    public function test_extracts_diff_block_from_ai_response(): void
    {
        $diffContent = "--- a/app/Http/Controllers/TestController.php\n+++ b/app/Http/Controllers/TestController.php\n@@ -10,3 +10,4 @@\n     public function show()\n     {\n+        \$this->authorize('view');\n         return view('test');";

        $client = $this->createMock(AiClientInterface::class);
        $client->method('isAvailable')->willReturn(true);
        $client->method('generate')->willReturn("Here's the fix:\n\n```diff\n{$diffContent}\n```");

        $generator = new AiPatchGenerator(
            $client,
            new PromptBuilder(),
            new PatchBuilder(),
        );

        $finding = Finding::high(
            check: 'route-authorization',
            message: 'Test finding',
            file: '/app/Http/Controllers/TestController.php',
            line: 10,
            context: [],
            fix_hint: 'Add auth',
        );

        $patch = $generator->generate($finding);

        $this->assertNotNull($patch);
        $this->assertStringContainsString('Generated by Guard', $patch->diff);
        $this->assertStringContainsString('authorize', $patch->diff);
    }

    public function test_falls_back_to_note_when_no_diff_or_code_extracted(): void
    {
        $client = $this->createMock(AiClientInterface::class);
        $client->method('isAvailable')->willReturn(true);
        $client->method('generate')->willReturn('You should add authorization to this route. Consider using middleware.');

        $generator = new AiPatchGenerator(
            $client,
            new PromptBuilder(),
            new PatchBuilder(),
        );

        $finding = Finding::high(
            check: 'route-authorization',
            message: 'Test finding',
            file: '/app/Http/Controllers/TestController.php',
            line: 10,
            context: [],
            fix_hint: 'Add auth',
        );

        $noteOut = null;
        $patch = $generator->generate($finding, $noteOut);

        $this->assertNull($patch);
        $this->assertNotNull($noteOut);
        $this->assertStringContainsString('Guard AI Fix Suggestion', $noteOut);
        $this->assertStringContainsString('route-authorization', $noteOut);
    }
}
